### ISSUE TITLE
Move from OAuth1.0 to OAuth2

### ISSUE THREAD

**Issue by ghaiklor** [drudge/passport-twitter-token#10]
We should move from old OAuth protocol to OAuth2. Twitter is support it, so I don't see issues here.

**Comment by ghaiklor** [comment]
@drudge you can add me to this package too. When I have free time I will update this package with refactor and test coverage. Also I hope that Twitter is moving to OAuth2.0 but seems that not. So we just left what we have.

**Comment by drudge** [comment]
Added you.
