### ISSUE TITLE
Fetch user email

### ISSUE THREAD

**Issue by munir131** [drudge/passport-twitter-token#16]
Twitter now allow to fetch user email with easy verification.
For that we need to change API url to `https://api.twitter.com/1.1/account/verify_credentials.json`
also in email array you added blank string at there need to change.
https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by drudge** [comment]
Please feel free to submit a PR with this functionality.

**Comment by ghaiklor** [comment]
@munir131 yeah, you can make a PR and become a contributor to this project 👍 Also, don't forget about tests ;)

**Comment by drudge** [comment]
Closed by #17.
