### ISSUE TITLE
_loadUserProfile error

### ISSUE THREAD

**Issue by antoineverger** [drudge/passport-twitter-token#5]
Hi,

to be consistent with passport-facebook-token, shouldn't you return a self.fail(err) instead of a self.error(err) in the callback for _loadUserProfile ?

That would return a 401 if authentication fails because of wrong credentials and at the moment it returns a 500.

Cheers

**Comment by juvaly** [comment]
Yes, should probably behave like the Facebook Token strategy?

https://github.com/drudge/passport-facebook-token/blob/master/lib/passport-facebook-token/strategy.js#L96

Also, should check for missing token to avoid even trying to load the user profile.

https://github.com/drudge/passport-facebook-token/blob/master/lib/passport-facebook-token/strategy.js#L91
